In [6]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import os

In [38]:
folder_path = "ML files"
file_path = os.path.join(folder_path , 'Melbourne_housing_FULL.csv')
df = pd.read_csv(file_path)
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [10]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [12]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [14]:
df.shape

(34857, 21)

In [39]:
col_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG',
        'Distance', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'CouncilArea', 'Regionname', 'Propertycount' , 'Price']
df =df[col_to_use]
df.head()

,Suburb,Rooms,Type,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount,Price
0,Abbotsford,2,h,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0,NaN
1,Abbotsford,2,h,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0,1480000.0
2,Abbotsford,2,h,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0,NaN
4,Abbotsford,3,h,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0,1465000.0

In [40]:
df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
Price             7610
dtype: int64

In [41]:
col_to_fill_zero = ['Distance' , 'Bedroom2' , 'Car','Bathroom' , 'Propertycount']
df[col_to_fill_zero] = df[col_to_fill_zero].fillna(0)

In [42]:
df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Distance             0
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        0
Price             7610
dtype: int64

In [43]:
df['Landsize'] = df['Landsize'].fillna(df['Landsize'].mean())
df['BuildingArea'] = df['BuildingArea'].fillna(df['BuildingArea'].mean())

In [44]:
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Distance            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
CouncilArea         3
Regionname          3
Propertycount       0
Price            7610
dtype: int64

In [45]:
df.dropna(inplace = True)
df.isna().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
Regionname       0
Propertycount    0
Price            0
dtype: int64

In [46]:
df = pd.get_dummies(df , drop_first=True).astype(int)
df.head()

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Price,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,2,2,1,1,202,160,4019,1480000,0,...,0,1,0,0,1,0,0,0,0,0
2,2,2,2,1,0,156,79,4019,1035000,0,...,0,1,0,0,1,0,0,0,0,0
4,3,2,3,2,0,134,150,4019,1465000,0,...,0,1,0,0,1,0,0,0,0,0
5,3,2,3,2,1,94,160,4019,850000,0,...,0,1,0,0,1,0,0,0,0,0
6,4,2,3,1,2,120,142,4019,1600000,0,...,0,1,0,0,1,0,0,0,0,0

In [47]:
df.shape

(27244, 745)

In [48]:
X  = df.drop('Price' , axis = 1)
Y = df.Price

In [50]:
X_train , X_test , Y_train , y_test = train_test_split(X ,Y ,test_size = 0.3 , random_state = 2)

In [51]:
len(X_train)

19070

In [52]:
len(X_test)

8174

In [53]:
# Training model without L1 and L2 Regularization
model = LinearRegression()
model.fit(X_train , Y_train)

LinearRegression()

In [55]:
model.score(X_test , y_test)

0.13413168587711655

In [56]:
model.score(X_train , Y_train) #look at the difference of acuracy between train and test splits.

0.6825862950046448

In [ ]:
#Model Training using L1 regularization

In [60]:
from sklearn import linear_model


Lasso_reg = linear_model.Lasso(alpha=50 , max_iter = 100 , tol = 1.0)

Lasso_reg.fit(X_train , Y_train)

Lasso(alpha=50, max_iter=100, tol=1.0)

In [62]:
Lasso_reg.score(X_train , Y_train)

0.6630752665724269

In [64]:
Lasso_reg.score(X_test , y_test)

0.6515203898007556

In [65]:
#Model Training using L2 regularization
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=50 , max_iter = 100 , tol = 1.0)
ridge_reg.fit(X_train , Y_train)

Ridge(alpha=50, max_iter=100, tol=1.0)

In [66]:
ridge_reg.score(X_test ,y_test)

0.6669747759118699

In [67]:
ridge_reg.score(X_train ,Y_train)

0.6619849633207062